### ISSUE TITLE
Task:  Update the artist bio images

### ISSUE THREAD

**Issue by GrungeElFz** [GrungeElFz/Astro_Liquid.Dreams#5]
#### Tasks:

Directory: `src/assets/images/`

- Replace the current `Rafael Manuel`'s image with the image from [LiQuid Dreams's post](https://www.instagram.com/p/C_wUXbRvehM)
- Replace the current `Norman Hernandez`'s image with the image from [LiQuid Dreams's post](https://www.instagram.com/p/C_txRR8PIJN)

___

Directory: `src/content/post/`

- Update `Rafael Manuel`'s image in the bio page
- Update `Norman Hernandez`'s image in the bio page

___

Note:

- Please, inspect the Instagram's post and look for the image source, as you cannot simply click to save it.
- Please, format the name of the incoming image files according to the current naming format in the repository.

**Comment by thihanmoekyaw** [comment]
Closing this issue since the update was merged. Thanks!

**Comment by GrungeElFz** [comment]
Appreciate it!

Merged and went live.

**Comment by GrungeElFz** [comment]
> @thihanmoekyaw: Closing this issue since the update was merged. Thanks!

Appreciate it!

___

MR: [#6 Update DJ Norman Herandez and Rafawl Manuel pictures for blogs](https://github.com/GrungeElFz/Astro_Liquid.Dreams/pull/6)
- ✅ MR [#6](https://github.com/GrungeElFz/Astro_Liquid.Dreams/pull/6) has been merged into `main`
- ✅ MR [#6](https://github.com/GrungeElFz/Astro_Liquid.Dreams/pull/6) has been tested and deployed to the production environment
